server:
  port: 8081

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:ratelimit}
    username: ${POSTGRES_USER:ratelimit}
    password: ${POSTGRES_PASSWORD:ratelimit}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

# # 應用層 token bucket：每個 IP 每分鐘 20 次
# ratelimit:
#   orders:
#     enabled: true
#     capacity: 20
#     refill-tokens: 20
#     refill-period: 1m

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      inventory:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers

ratelimit:
  orders:
    enabled: true
    algorithm: token-bucket      # fixed-window | token-bucket
    fixed-window:
      limit: 20
      window: 1m
    token-bucket:
      capacity: 20
      refill-tokens: 20
      refill-period: 1m
      
logging:
  level:
    root: INFO
    com.willie.ratelimit.order.adapter.in.web.ratelimit: DEBUG
  